const SamplePermits = [
  {
    id: 1,
    name: "John Doe",
    address: "123 Main St, Springfield, IL",
    phoneNumber: "(555) 123-4567",
    emailAddress: "johndoe@example.com",
    permitType: "Building",
    permitNumber: "R123456",
    requestDate: "2024-08-15",
    permitExpiryDate: "2025-08-15",
    status: "Approved",
    propertyAddress: "123 Main St, Springfield, IL",
    lotNumber: "12",
    blockNumber: "5",
    descriptionOfRequest: "Renovation of the kitchen and living room.",
    reasonForRequest: "Updating outdated fixtures and improving layout.",
    startDate: "2024-09-01",
    endDate: "2024-10-01",
    plansAndDrawings: "URL to plans and drawings",
    contracts: "URL to contracts",
    photographs: "URL to photographs",
    otherPermits: "URL to other permits",
    uploadedDocuments: [
      "https://picsum.photos/800/600?random=1",
      "https://picsum.photos/800/600?random=2",
      "https://picsum.photos/800/600?random=3",
    ],
    feeAmount: "$150.00",
    paymentStatus: "Paid",
    receipt: "URL to receipt",
    codeCompliance: "Compliant with local regulations",
    inspectionDate: "2024-08-20",
    inspectionStatus: "Passed",
    additionalComments: "All required documents have been submitted.",
    reviewersName: "Jane Smith",
    approvalDate: "2024-08-20",
    finalApprovalStatus: "Approved",
    approveDate: "2024-09-01",
    completionDate: "2024-09-02",
    details: "Permit already received",
    issueDate: "2024-09-02",
  },
];

export default SamplePermits;
